name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies for Tauri (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: bun install

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Build the app
        run: bunx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} ${{ runner.arch }} artifacts
          # No .app because it's pretty big and .dmg is nicer
          path: |
            src-tauri/target/release/bundle/*/*.dmg
            src-tauri/target/release/bundle/*/*.AppImage
            src-tauri/target/release/bundle/*/*.deb
            src-tauri/target/release/bundle/*/*.msi
      # - name: Build the app
      #   uses: tauri-apps/tauri-action@v0
      #   working-directory: src/frontend
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
      #     releaseName: 'v__VERSION__'
      #     releaseBody: 'See the assets to download this version and install.'
      #     releaseDraft: true
      #     prerelease: false
